package com.dfggking.entity;
// Generated 2017-7-13 14:55:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dfgg")
public class User implements java.io.Serializable {
    
    /**
     * @author dfggking@hotmail.com
     * @create 2017-09-29
     * @since 1.0
     */
    private static final long serialVersionUID = 1L;
    private String id;
    private String nickName;
    private String password;
    private String email;
    private String status;
    private Date createTime;
    private Date updateTime;
    
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 11)
    public String getId(){
        return this.id;
    }
    
    public void setId(String id){
        this.id = id;
    }
    
    @Column(name = "nick_name", nullable = false, length = 20)
    public String getNickname(){
        return this.nickName;
    }
    
    public void setNickname(String nickName){
        this.nickName = nickName;
    }
    
    @Column(name = "password", nullable = false, length = 16)
    public String getPassword(){
        return this.password;
    }
    
    public void setPassword(String password){
        this.password = password;
    }
    
    @Column(name = "email", length = 50)
    public String getEmail(){
        return this.email;
    }
    
    public void setEmail(String email){
        this.email = email;
    }
    
    @Column(name = "status", length = 4)
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name = "create_time")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name = "update_time")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    
    
}
